model:
  name: "PP-StructureV3"
  provider: "paddleocr"
  keys:
    - lot_no
    - block
    - address
    - model_selected
    - elevation
    - garage_swing
    - external_structure
    - optional_notes
